spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:templates/
    suffix: .ftl
    cache: false